version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.40
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWORD: pass
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306

